CREATE DATABASE chat;

USE chat;

CREATE TABLE users(
  id INT NOT NULL AUTO_INCREMENT DEFAULT NULL,
  name VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE rooms(
  id INT NOT NULL AUTO_INCREMENT DEFAULT NULL,
  name VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE messages(
  id INT NOT NULL AUTO_INCREMENT DEFAULT NULL,
  text VARCHAR(140) NULL DEFAULT NULL,
  userId INT,
  roomId INT,
  PRIMARY KEY(id),
  INDEX(userId, roomId),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (roomId) REFERENCES rooms(id) ON DELETE CASCADE
);
